---
ID: "78d6db25-0909-4fca-9476-ac029380ffcf"
Parent: "78abb615-9c8b-48e0-906c-cd0d141bc379"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Content Author Tokens/Module Root/Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180822T145529Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
